name: Rust

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Pkgs
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-program-options-dev libelf-dev lcov libbpf-dev      
    - name: Install libbpf from source
      run: bpf_conformance/.github/scripts/build-libbpf.sh
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build bpf_conformance
      run: |
        cd bpf_conformance
        cmake -S . -B build
        cmake --build build
    - name: Test with bpf_conformance
      run: |        
        cd bpf_conformance/build/bin
        RUST_BACKTRACE=1 ./bpf_conformance_runner --debug false --test_file_directory ../tests --plugin_path ../../../target/debug/emem 
